Add more detailed errors to clarify hash issues
comp500/packwiz pull request #9
Opened 2020-10-19 22:24 UTC by Draylar

This PR adds tweaked error messages for when hashes don't match up. 

I also noticed some hashes come back (might be from CF or Discord?) as uppercase when hash-providing tools claim they are lowercase. I added a special warning for it.

![image](https://user-images.githubusercontent.com/17728338/96518175-f221db00-122f-11eb-996c-b363added29c.png)

2020-10-19 22:27 UTC, Draylar commented
Scratch that, just going to remove the special handling for uppercasing. One second.

2020-10-20 00:24 UTC, comp500 commented
Uppercase hex haha yes

2020-10-20 00:27 UTC, comp500 requested changes
Looks good (although I should probably pass this data up the chain a bit, I'll probably clean it up in the Rust port), could just be cleaned up a bit.

2020-10-20 00:27 UTC, comp500 commented on core/mod.go
> +		return errors.New(fmt.Sprintf("Hash of downloaded file does not match with expected hash!\n download hash: %s\n expected hash: %s\n", calculatedHash, m.Download.Hash))
```suggestion
		return fmt.Errorf("Hash of downloaded file does not match with expected hash!\n download hash: %s\n expected hash: %s\n", calculatedHash, m.Download.Hash)
```
Just a bit cleaner :)

2020-10-20 16:45 UTC, comp500 approved these changes

2020-10-20 16:45 UTC, merged